export const GET_TRACKINGS = 'GET_TRACKINGS';
export const SYNC_TRACKINGS = 'SYNC_TRACKINGS';
export const TRACKINGS_LOADING = 'TRACKINGS_LOADING';
export const TRACKINGS_SYNCING = 'TRACKINGS_SYNCING';
